CREATE TABLE IF NOT EXISTS catalog (
 id INTEGER PRIMARY KEY CHECK(id = 1), live TEXT NOT NULL, draft TEXT NOT NULL,
 revision INTEGER NOT NULL DEFAULT 0, published_at TEXT
);
CREATE TABLE IF NOT EXISTS history (id INTEGER PRIMARY KEY AUTOINCREMENT, catalog TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS login_limits (key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS photos (id TEXT PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL, data BLOB NOT NULL, created_at TEXT NOT NULL);
