import {escapeHTML as e,validateCatalog,photoURL,dishImage,money} from '/shared.js';
const $=s=>document.querySelector(s);
let catalog,revision,publishedAt,dirty=false,tab='dishes',photos=[],editor=null,filterCategory='all',filterText='',busy=false;
const items=()=>catalog.categories.flatMap(c=>c.items);
const id=prefix=>prefix+'-'+crypto.randomUUID().slice(0,8);
function status(message,error=false){$('#admin-status').textContent=message;$('#admin-status').hidden=!message;$('#admin-status').className=error?'error':'notice';}
function flash(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,4000);}
function markDirty(){dirty=true;saveState();}
function saveState(){$('#save-state').textContent=`${dirty?'Unsaved changes in this page':'Draft saved on server'} · ${publishedAt?'Last published '+new Date(publishedAt).toLocaleString():'Initial catalog · not yet published from dashboard'}`;}
async function api(path,options={}){const res=await fetch('/api/admin/'+path,{...options,headers:{...(options.body&&typeof options.body==='string'?{'Content-Type':'application/json'}:{}),...options.headers}});let data;try{data=await res.json();}catch{throw Error('Owner publishing is unavailable. Run the Cloudflare service or finish the setup guide.');}if(!res.ok){if(res.status===401&&path!=='login'){status('Your session expired. Download a backup of unsaved changes, then sign in again.',true);}throw Error(data.error||'The request failed. Please try again.');}return data;}
async function operation(fn){if(busy)return;busy=true;document.querySelectorAll('#save,#publish,#confirm-publish,#preview,#logout').forEach(b=>b.disabled=true);try{await fn();}catch(err){status(err.message,true);}finally{busy=false;document.querySelectorAll('#save,#publish,#confirm-publish,#preview,#logout').forEach(b=>b.disabled=false);}}
async function load(){const data=await api('draft');catalog=data.catalog;revision=data.revision;publishedAt=data.publishedAt;photos=(await api('photos')).photos;dirty=false;$('#login').hidden=true;$('#dashboard').hidden=false;status('');saveState();render();}
function field(label,name,value,type='text',max=300){return `<label>${e(label)}<input name="${name}" type="${type}" value="${e(value??'')}" ${type==='number'?'min="0" max="100000" step="0.01"':`maxlength="${max}"`} ${['name','phone','email','whatsappNumber','alternatePhone','address'].includes(name)?'required':''}></label>`;}
function area(label,name,value,max=500){return `<label class="full">${e(label)}<textarea name="${name}" rows="3" maxlength="${max}">${e(value)}</textarea></label>`;}
function check(label,name,value){return `<label class="checkbox-label full"><input type="checkbox" name="${name}" ${value?'checked':''}>${e(label)}</label>`;}
function imageSelect(value){return `<label class="full">Dish / package photo<select name="image"><option value="">Photo pending</option>${catalog.photoCredits.map(p=>`<option value="${e(p.file)}" ${p.file===value?'selected':''}>Stock illustration · ${e(p.file)}</option>`).join('')}${photos.map(p=>`<option value="/media/${e(p.id)}" ${'/media/'+p.id===value?'selected':''}>${e(p.name)}</option>`).join('')}</select><small>Choose a matching image. Upload new photographs in Photos first.</small></label>${value?`<img class="edit-preview" src="${e(photoURL(value))}" alt="Current photo">`:''}`;}
function visibility(obj){return obj.visible?'Visible':'Hidden';}
function render(){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===tab)));
 const panel=$('#admin-panel');
 if(tab==='dishes'){
  panel.innerHTML=`<div class="custom-heading"><h2>Dishes</h2><button class="button primary" id="add-dish">+ Add dish</button></div><div class="form-grid"><label>Category<select id="dish-category"><option value="all">All categories</option>${catalog.categories.map(c=>`<option value="${e(c.id)}" ${c.id===filterCategory?'selected':''}>${e(c.name)}</option>`).join('')}</select></label><label>Find a dish<input id="dish-search" type="search" value="${e(filterText)}" placeholder="Search by name"></label></div><div id="admin-dish-list" class="admin-list"></div>`;renderDishList();
 }else if(tab==='categories')panel.innerHTML=`<div class="custom-heading"><h2>Categories</h2><button class="button primary" id="add-category">+ Add category</button></div><p class="muted">Hidden categories and their dishes won’t appear on the customer site. Move categories with the arrows.</p><div class="admin-list">${catalog.categories.map((c,i)=>`<div class="admin-row"><div><strong>${e(c.name)}</strong><small>${c.items.length} dishes · ${visibility(c)}</small></div><div class="admin-row-buttons"><button class="icon-button" data-move="${e(c.id)}" data-dir="-1" aria-label="Move ${e(c.name)} up" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-move="${e(c.id)}" data-dir="1" aria-label="Move ${e(c.name)} down" ${i===catalog.categories.length-1?'disabled':''}>↓</button><button class="button quiet" data-edit-category="${e(c.id)}">Edit</button></div></div>`).join('')}</div>`;
 else if(tab==='packages')panel.innerHTML=`<div class="custom-heading"><h2>Packages</h2><button class="button primary" id="add-package">+ Add package</button></div><p class="muted">Edit a package’s inclusions and the actual dishes customers can choose for each one.</p><div class="admin-list">${catalog.plans.map(p=>`<div class="admin-row"><div><strong>${e(p.name)}</strong><small>${p.slots.length} inclusions · ${visibility(p)} · ${p.pricePerPlate===null?'Quote requested':money(p.pricePerPlate)+'/guest'}</small></div><div class="admin-row-buttons"><button class="button quiet" data-slots="${e(p.id)}">Dish choices</button><button class="button quiet" data-edit-package="${e(p.id)}">Edit</button></div></div>`).join('')}</div>`;
 else if(tab==='photos')panel.innerHTML=`<h2>Your photo library.</h2><p class="muted">Upload your own matching JPG, PNG or WebP photographs. They are resized on your phone before upload (up to 1,000 px and 350 KB). Maximum 100 uploaded photos. Uploads are stored on the server; use a dish or package’s Edit button to assign them.</p><label class="button quiet">Upload a photo<input id="photo-upload" type="file" accept="image/jpeg,image/png,image/webp" hidden></label><p id="upload-status" role="status"></p><div class="photo-grid">${photos.map(p=>`<figure><img src="/media/${e(p.id)}" alt="${e(p.name)}" loading="lazy"><figcaption><p>${e(p.name)}</p></figcaption></figure>`).join('')}</div><h3>Stock serving inspiration</h3><p class="muted">Only use these for matching dishes. They must be labelled illustrative.</p><div class="photo-grid">${catalog.photoCredits.map(p=>`<figure><img src="${e(photoURL(p.file))}" alt="${e(p.file)}" loading="lazy"><figcaption><p>${e(p.file)} · ${e(p.creator)}</p></figcaption></figure>`).join('')}</div>`;
 else if(tab==='business'){
  const b=catalog.business;panel.innerHTML=`<h2>Business & prices</h2><form id="business-form"><div class="form-grid">${field('Business name','name',b.name)}${field('Tagline','tagline',b.tagline)}${area('Description','description',b.description,600)}${field('Main phone (+country code)','phone',b.phone,'tel')}${field('Alternate phone','alternatePhone',b.alternatePhone,'tel')}${field('WhatsApp number (country code, digits only)','whatsappNumber',b.whatsappNumber,'tel')}${field('Email','email',b.email,'email')}${field('Address','address',b.address)}${field('Minimum guests (10–5,000)','minimumGuests',catalog.ordering.minimumGuests,'number')}${area('Quote / price note','priceNote',catalog.ordering.priceNote)}${imageSelect(b.heroImage)}${check('Hero photo is illustrative','heroIllustrative',b.heroIllustrative!==false)}${check('I approve the entered prices for public display (leave off to request quotes)','pricesApproved',catalog.ordering.pricesApproved)}</div><div class="notice">Blank prices always show “Quote on request”. Approved prices are estimates; the owner still confirms a complete quote.</div><button class="button primary" type="submit">Apply business details to draft</button></form>`;
 }
}
function renderDishList(){const list=catalog.categories.filter(c=>filterCategory==='all'||c.id===filterCategory).flatMap(c=>c.items.map(i=>({...i,categoryName:c.name}))).filter(i=>i.name.toLowerCase().includes(filterText.toLowerCase()));$('#admin-dish-list').innerHTML=list.map(i=>`<div class="admin-row"><img src="${e(dishImage(i))}" alt="${e(i.name)}" loading="lazy"><div><strong>${e(i.name)}</strong><small>${e(i.categoryName)} · ${visibility(i)}<br>${i.price===null?'Quote requested':e(money(i.price))+'/guest'}</small></div><button class="button quiet" data-edit-dish="${e(i.id)}">Edit</button></div>`).join('')||'<p class="empty">No matching dishes.</p>';}
function edit(type,obj=null,parent=null){
 editor={type,obj,parent};$('#edit-error').hidden=true;$('#edit-title').textContent=(obj?'Edit ':'Add ')+type;
 const x=obj||{name:'',description:'',visible:true,image:'',price:null,pricePerPlate:null,badge:'',illustrative:true};let fields='';
 if(type==='dish')fields=`${field('Dish name','name',x.name)}<label>Category<select name="category">${catalog.categories.map(c=>`<option value="${e(c.id)}" ${c.items.some(i=>i.id===x.id)||(!obj&&c.id===filterCategory)?'selected':''}>${e(c.name)}</option>`).join('')}</select></label>${area('Description','description',x.description)}${field('Price per guest (blank = quote)','price',x.price,'number')}${imageSelect(x.image)}${check('Photo is illustrative (required for stock photos)','illustrative',x.illustrative)}${check('Visible to customers','visible',x.visible)}`;
 if(type==='category')fields=`${field('Category name','name',x.name)}${area('Description','description',x.description)}${check('Visible to customers','visible',x.visible)}`;
 if(type==='package')fields=`${field('Package name','name',x.name)}${field('Short badge','badge',x.badge,'text',60)}${area('Description','description',x.description)}${field('Price per guest (blank = quote)','pricePerPlate',x.pricePerPlate,'number')}${imageSelect(x.image)}${check('Photo is illustrative','illustrative',x.illustrative!==false)}${check('Visible to customers','visible',x.visible)}<p class="full muted">Use “Dish choices” after creating the package to add inclusions and selectable dishes. New packages start hidden until they have inclusions.</p>`;
 if(type==='inclusion'){const slot=obj||{label:'',count:1,itemIds:[]};fields=`${field('Inclusion name (e.g. Any 2 sweets)','label',slot.label,'text',100)}<label>Number of dishes to choose<input type="number" name="count" min="1" max="5" value="${slot.count}" required></label><label class="full">Find choices<input id="slot-search" type="search" placeholder="Filter dishes"></label><p class="muted full">Tick all the dishes customers may choose from. They choose only the number set above.</p><div class="full" id="slot-options">${catalog.categories.map(c=>`<div><h3>${e(c.name)}</h3>${c.items.map(i=>`<label class="checkbox-label slot-option" data-name="${e(i.name.toLowerCase())}"><input type="checkbox" name="slotItem" value="${e(i.id)}" ${slot.itemIds.includes(i.id)?'checked':''}>${e(i.name)}${i.visible&&c.visible?'':' (hidden)'}</label>`).join('')}</div>`).join('')}</div>`;}
 $('#edit-fields').innerHTML=`<div class="form-grid">${fields}</div>`;$('#edit-dialog').showModal();
}
function showSlots(packageId){tab='packages';const p=catalog.plans.find(p=>p.id===packageId);$('#admin-panel').innerHTML=`<div class="custom-heading"><div><button class="text-link" data-tab="packages">← All packages</button><h2>${e(p.name)} choices</h2></div><button class="button primary" data-add-slot="${e(p.id)}">+ Inclusion</button></div><div class="admin-list">${p.slots.map(s=>`<div class="admin-row"><div><strong>${e(s.label)}</strong><small>Choose ${s.count} from ${s.itemIds.length} dishes</small></div><div class="admin-row-buttons"><button class="button quiet" data-edit-slot="${e(s.id)}" data-parent="${e(p.id)}">Edit</button><button class="button quiet danger" data-remove-slot="${e(s.id)}" data-parent="${e(p.id)}">Remove</button></div></div>`).join('')}</div>`;}
async function save(){validateCatalog(catalog);const data=await api('draft',{method:'PUT',body:JSON.stringify({catalog,revision})});revision=data.revision;dirty=false;saveState();status('Draft saved on the server. Customer catalog is unchanged until you publish.');}
async function preparePublish(){if(dirty)await save();validateCatalog(catalog);const visible=catalog.categories.filter(c=>c.visible).flatMap(c=>c.items.filter(i=>i.visible));$('#confirm-body').innerHTML=`<p>This will update your customer catalog immediately.</p><div class="notice">${catalog.plans.filter(p=>p.visible).length} visible packages · ${visible.length} visible dishes<br>${catalog.ordering.pricesApproved?'Approved prices will be displayed where entered.':'Prices remain quote-on-request.'}<br>${visible.filter(i=>!i.image).length} dishes are clearly labelled “Photo pending”.</div><p>Check your <a href="/?preview=1" target="_blank" rel="noopener">saved draft preview ↗</a> before publishing. Make sure the WhatsApp number is correct: <strong>${e(catalog.business.whatsappNumber)}</strong>.</p>`;$('#confirm-dialog').showModal();}
async function upload(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose a JPG, PNG or WebP. On iPhone, export HEIC photos as JPEG first.');if(file.size>20000000)throw Error('Choose a photo smaller than 20 MB.');$('#upload-status').textContent='Preparing your photo…';const bitmap=await createImageBitmap(file);const scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let blob;for(const quality of [.82,.65,.45,.25]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));if(blob&&blob.size<=350000)break;}if(!blob||blob.size>350000)throw Error('This image is too detailed. Try a smaller image.');$('#upload-status').textContent='Uploading to your photo library…';await api('photos',{method:'POST',headers:{'Content-Type':'image/jpeg','X-Photo-Name':encodeURIComponent(file.name)},body:blob});photos=(await api('photos')).photos;render();flash('Photo uploaded. Edit a dish or package to assign it.');}
document.addEventListener('submit',ev=>{
 if(ev.target.id==='login-form'){ev.preventDefault();operation(async()=>{const button=ev.target.querySelector('button');button.disabled=true;try{await api('login',{method:'POST',body:JSON.stringify({password:ev.target.elements.password.value})});ev.target.reset();await load();}finally{button.disabled=false;}});}
 if(ev.target.id==='business-form'){ev.preventDefault();try{const d=Object.fromEntries(new FormData(ev.target));const next=structuredClone(catalog);for(const k of ['name','tagline','description','phone','alternatePhone','whatsappNumber','email','address'])next.business[k]=d[k].trim();next.business.heroImage=d.image;next.business.heroIllustrative=Boolean(d.heroIllustrative);next.ordering.minimumGuests=Number(d.minimumGuests);next.ordering.pricesApproved=Boolean(d.pricesApproved);next.ordering.priceNote=d.priceNote;validateCatalog(next);catalog=next;markDirty();flash('Business details applied. Save and publish when ready.');}catch(err){status(err.message,true);}}
 if(ev.target.id==='edit-form'){
  ev.preventDefault();try{
   const form=new FormData(ev.target),d=Object.fromEntries(form),{type,obj,parent}=editor;const next=structuredClone(catalog);let x=obj?{...obj}:{id:id(type),description:'',visible:true};
   if(type==='inclusion'){
    x={...x,label:d.label.trim(),count:Number(d.count),itemIds:form.getAll('slotItem')};if(!x.label||x.itemIds.length<x.count)throw Error('Enter a label and enough dish choices.');const p=next.plans.find(p=>p.id===parent);if(p.slots.some(s=>s.label===x.label&&s.id!==x.id))throw Error('Each inclusion needs a different label.');if(obj)p.slots[p.slots.findIndex(s=>s.id===obj.id)]=x;else p.slots.push(x);p.includes=p.slots.map(s=>s.label);
   }else {
    x={...x,name:d.name.trim(),description:d.description.trim(),visible:Boolean(d.visible)};if(!x.name)throw Error('Enter a name.');
    if(type==='dish'){
     x={...x,image:d.image,illustrative:Boolean(d.illustrative)||Boolean(d.image&&!d.image.startsWith('/media/')),price:d.price===''?null:Number(d.price),unit:'guest'};
     if(obj)for(const cat of next.categories)cat.items=cat.items.filter(i=>i.id!==obj.id);
     next.categories.find(c=>c.id===d.category).items.push(x);
    }else if(type==='category'){if(obj)next.categories[next.categories.findIndex(c=>c.id===x.id)]=x;else next.categories.push({...x,items:[]});}
    else if(type==='package'){
     x={...x,badge:d.badge.trim(),pricePerPlate:d.pricePerPlate===''?null:Number(d.pricePerPlate),image:d.image,illustrative:Boolean(d.illustrative)||Boolean(d.image&&!d.image.startsWith('/media/'))};
     if(obj)next.plans[next.plans.findIndex(p=>p.id===x.id)]=x;
     else {const first=items()[0];if(!first)throw Error('Add a dish before creating a package.');next.plans.push({...x,visible:false,includes:['Choose a dish'],slots:[{id:'slot-1',label:'Choose a dish',count:1,itemIds:[first.id]}]});}
    }
   }
   validateCatalog(next);catalog=next;markDirty();$('#edit-dialog').close();if(type==='inclusion')showSlots(parent);else render();flash('Changes applied to draft.');
  }catch(err){$('#edit-error').textContent=err.message;$('#edit-error').hidden=false;}
 }
});
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-close'))b.closest('dialog').close();
 if(!catalog)return;
 if(b.dataset.tab){tab=b.dataset.tab;render();}
 if(b.id==='add-dish')edit('dish');if(b.dataset.editDish)edit('dish',items().find(i=>i.id===b.dataset.editDish));
 if(b.id==='add-category')edit('category');if(b.dataset.editCategory)edit('category',catalog.categories.find(c=>c.id===b.dataset.editCategory));
 if(b.id==='add-package')edit('package');if(b.dataset.editPackage)edit('package',catalog.plans.find(p=>p.id===b.dataset.editPackage));
 if(b.dataset.slots)showSlots(b.dataset.slots);
 if(b.dataset.addSlot)edit('inclusion',null,b.dataset.addSlot);
 if(b.dataset.editSlot)edit('inclusion',catalog.plans.find(p=>p.id===b.dataset.parent).slots.find(s=>s.id===b.dataset.editSlot),b.dataset.parent);
 if(b.dataset.removeSlot){const p=catalog.plans.find(p=>p.id===b.dataset.parent);if(p.slots.length===1){status('Keep at least one inclusion. Hide the package if you no longer offer it.',true);return;}p.slots=p.slots.filter(s=>s.id!==b.dataset.removeSlot);p.includes=p.slots.map(s=>s.label);markDirty();showSlots(p.id);}
 if(b.dataset.move){const n=catalog.categories.findIndex(c=>c.id===b.dataset.move),to=n+Number(b.dataset.dir);if(to>=0&&to<catalog.categories.length){[catalog.categories[n],catalog.categories[to]]=[catalog.categories[to],catalog.categories[n]];markDirty();render();}}
 if(b.id==='save')operation(save);
 if(b.id==='preview')operation(async()=>{if(dirty){status('Save your latest changes first, then preview the saved draft.',true);return;}window.open('/?preview=1','_blank','noopener');});
 if(b.id==='publish')operation(preparePublish);
 if(b.id==='confirm-publish')operation(async()=>{const data=await api('publish',{method:'POST',body:JSON.stringify({revision})});revision=data.revision;publishedAt=data.publishedAt;$('#confirm-dialog').close();saveState();status('Published. Customers will see the updated catalog when they open or refresh the site.');});
 if(b.id==='export'){const blob=new Blob([JSON.stringify(catalog,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sri-vinayaka-catalog-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 if(b.id==='history')operation(async()=>{const {history}=await api('history');$('#history-list').innerHTML=history.map(h=>`<div class="admin-row"><div><strong>Before ${e(new Date(h.created_at).toLocaleString())}</strong><small>Previous published catalog</small></div><button class="button quiet" data-restore="${h.id}">Restore draft</button></div>`).join('')||'<p class="notice">Your previous version will appear here after your first publish.</p>';$('#history-dialog').showModal();});
 if(b.dataset.restore)operation(async()=>{if(dirty)throw Error('Save or download your current edits before restoring a previous version.');await api('restore',{method:'POST',body:JSON.stringify({id:Number(b.dataset.restore),revision})});await load();$('#history-dialog').close();status('Previous catalog restored to draft. Preview and publish to make it live.');});
 if(b.id==='logout')operation(async()=>{if(dirty)throw Error('Save your changes or download a backup before signing out.');await api('logout',{method:'POST',body:'{}'});catalog=null;$('#dashboard').hidden=true;$('#login').hidden=false;status('Signed out.');});
});
document.addEventListener('input',ev=>{if(ev.target.id==='dish-search'){filterText=ev.target.value;renderDishList();}if(ev.target.id==='slot-search'){const q=ev.target.value.toLowerCase();document.querySelectorAll('.slot-option').forEach(x=>x.hidden=!x.dataset.name.includes(q));}});
document.addEventListener('change',ev=>{if(ev.target.id==='dish-category'){filterCategory=ev.target.value;renderDishList();}if(ev.target.id==='photo-upload'&&ev.target.files[0])operation(()=>upload(ev.target.files[0]));});
window.addEventListener('beforeunload',ev=>{if(dirty){ev.preventDefault();ev.returnValue='';}});
(async()=>{try{await api('session');await load();}catch(err){$('#login').hidden=false;status(err.message.includes('sign in')?'':err.message,Boolean(!err.message.includes('sign in')));}})();
